[package]
name = "simple-osd-common"
version = "0.1.0"
authors = ["Alexander Bantyev <balsoft@balsoft.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnotify = "1.0.3"
configparser = "1.0.0"
xdg = "2.1"
